version: "3.8"

services:
  django:
    build:
      context: .
    command: python3 manage.py runserver 0.0.0.0:80
    restart: unless-stopped
    depends_on:
      - db
      - redis
      - rabbitmq
    env_file: .env
    environment:
      DATABASE_URL: postgres://django:${POSTGRES_PASSWORD}@db:5432/django
      CACHE_URL: redis://:${REDIS_PASSWORD}@redis:6379/0
      CELERY_BROKER_URL: redis://:${REDIS_PASSWORD}@redis:6379/1
      CELERY_RESULT_BACKEND: redis://:${REDIS_PASSWORD}@redis:6379/2
      WEBSOCKET_CHANNEL_LAYERS: redis://:${REDIS_PASSWORD}@redis:6379/3
      RABBITMQ_URL: amqp://${RABBITMQ_USER:?}:${RABBITMQ_PASSWORD:?}@rabbitmq:5672/%2F
      EMAIL_URL: ${EMAIL_URL:-filemail:////tmp/mail/}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS:-}

  celery_worker:
    extends:
      service: django
    depends_on:
      - db
      - redis
      - rabbitmq
    command: celery -A moneymanager worker --autoscale 2,1 --loglevel INFO --events

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5432"
    volumes:
      - database_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: redis-server --loglevel notice --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
    expose:
      - "6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:?}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:?}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 536870912
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - default
      - notifications_service_network
    expose:
      - 5672
      - 15672

volumes:
  database_data:
  rabbitmq_data:

networks:
  notifications_service_network:
    name: ${NOTIFICATIONS_SERVICE_NETWORK:-moneyger-notifications}
    external: ${NOTIFICATIONS_SERVICE_NETWORK_EXTERNAL:-false}
