version: "3.8"

services:
  django:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:80
    restart: unless-stopped
    depends_on:
      - db
      - redis
    secrets:
      - postgres_password
    env_file: .env
    environment:
      DEBUG: "false"
      DATABASE_URL: postgres://django:{{secrets.postgres_password}}@db:5432/django
      CELERY_BROKER_URL: redis://:{{secrets.redis_password}}@redis:6379/
      CELERY_RESULT_BACKEND: redis://:{{secrets.redis_password}}@redis:6379/
    ports:
      - "${PORT:-80}:80"

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    secrets:
      - postgres_password
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    expose:
      - "5432"
    volumes:
      - database_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    secrets:
      - redis_password
    command: redis-server --loglevel warning --requirepass {{secrets.redis_password}}
    restart: unless-stopped
    expose:
      - "6379"

secrets:
  postgres_password:
    environment: "POSTGRES_PASSWORD"
  redis_password:
    environment: "REDIS_PASSWORD"
  