version: "3.8"

services:
  django:
    build:
      context: .
    command: python3 manage.py runserver 0.0.0.0:80
    restart: unless-stopped
    depends_on:
      - db
      - redis
    env_file: .env
    environment:
      DATABASE_URL: postgres://django:${POSTGRES_PASSWORD}@db:5432/django
      CACHE_BACKEND: django.core.cache.backends.redis.RedisCache
      CACHE_LOCATION: redis://:${REDIS_PASSWORD}@redis:6379/
      CELERY_BROKER_URL: redis://:${REDIS_PASSWORD}@redis:6379/
      CELERY_RESULT_BACKEND: redis://:${REDIS_PASSWORD}@redis:6379/
    ports:
      - "${PORT:-80}:80"

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5432"
    volumes:
      - database_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: redis-server --loglevel warning --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
    expose:
      - "6379"

volumes:
  database_data:
