version: "3.8"

services:
  django:
    extends:
      file: docker-compose.yml
      service: django
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
      - redis
      - rabbitmq
    volumes:
      - ./:/app:ro
    restart: "no"
    environment:
      DEBUG: True
    ports:
      - "${PORT:-80}:80"

  celery_worker:
    extends:
      file: docker-compose.yml
      service: celery_worker
    depends_on:
      - db
      - redis
      - rabbitmq
    environment:
      DEBUG: True
    command: celery -A moneymanager worker --loglevel INFO --autoscale 2,1
    restart: "no"
    volumes:
      - ./:/app:ro

  db:
    extends:
      file: docker-compose.yml
      service: db
    restart: "no"
    ports:
      - "5432:5432"

  redis:
    extends:
      file: docker-compose.yml
      service: redis
    command: redis-server --loglevel debug --requirepass ${REDIS_PASSWORD}
    restart: "no"
    ports:
      - "6379:6379"

  rabbitmq:
    extends:
      file: docker-compose.yml
      service: rabbitmq
    restart: "no"
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  database_data:
  rabbitmq_data:

networks:
  notifications_service_network:
    name: ${NOTIFICATIONS_SERVICE_NETWORK:-moneyger-notifications}
    external: ${NOTIFICATIONS_SERVICE_NETWORK_EXTERNAL:-false}
