[tool.black]
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  migrations/
  | settings.py
)
'''

[tool.isort]
profile = "black"
extend_skip_glob = ["*/migrations/*", "*/settings.py"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "moneymanager.settings"
python_files = ["test*.py"]
env = [
  "SECRET_KEY=test-secret-key",
  "ALLOWED_HOSTS=*",
  "CACHE_BACKEND=django.core.cache.backends.locmem.LocMemCache",
  "CELERY_BROKER_URL=memory://",
  "CELERY_RESULT_BACKEND=rpc://",
]
