# Generated by Django 4.2.3 on 2023-07-31 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_remove_transaction_last_modified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltransaction",
            name="comment",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicaltransactioncategory",
            name="icon",
            field=models.CharField(blank=True, default="", max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="comment",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transactioncategory",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transactioncategory",
            name="icon",
            field=models.CharField(blank=True, default="", max_length=64),
            preserve_default=False,
        ),
    ]
