# Generated by Django 4.2.3 on 2023-08-01 14:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_historicaltransaction_account_transaction_account_and_more"),
    ]

    operations = [
        migrations.RunSQL("DELETE FROM core_transaction WHERE category_id IS NULL;")
    ]
