# Generated by Django 4.2.3 on 2023-08-03 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_transactioncategory_parent_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltransaction",
            name="amount",
            field=models.BigIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.BigIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
