# Generated by Django 4.2.3 on 2023-08-30 07:12

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_historicaltransaction_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltransaction",
            name="transaction_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                validators=[
                    django.core.validators.MaxValueValidator(django.utils.timezone.now)
                ],
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                validators=[
                    django.core.validators.MaxValueValidator(django.utils.timezone.now)
                ],
            ),
        ),
    ]
