# Generated by Django 4.2.3 on 2023-10-18 09:28

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_historicaltransaction_transaction_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltransactioncategory",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=18, samples=None
            ),
        ),
        migrations.AlterField(
            model_name="transactioncategory",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=18, samples=None
            ),
        ),
    ]
