# Generated by Django 4.2.3 on 2023-10-18 10:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_historicaltransactioncategory_color_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicaltransactioncategory",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Category",
                "verbose_name_plural": "historical Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="transactioncategory",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
