# Generated by Django 4.2.3 on 2023-08-17 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="session_ttl",
            field=models.DurationField(
                choices=[
                    (datetime.timedelta(days=1), "Day"),
                    (datetime.timedelta(days=7), "Week"),
                    (datetime.timedelta(days=30), "Month"),
                ],
                default=datetime.timedelta(days=7),
            ),
        ),
    ]
