# Generated by Django 4.2.3 on 2023-08-17 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_account_session_ttl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="session_ttl",
            field=models.DurationField(
                choices=[
                    (datetime.timedelta(days=1), "1 day"),
                    (datetime.timedelta(days=7), "1 week"),
                    (datetime.timedelta(days=30), "1 month"),
                ],
                default=datetime.timedelta(days=7),
            ),
        ),
    ]
