# Generated by Django 4.2.3 on 2023-09-02 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_account_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="session_ttl",
        ),
    ]
