# Generated by Django 4.2.3 on 2023-07-28 12:34

import colorfield.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("IN", "Income"), ("OUT", "Outcome")], max_length=3
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("display_order", models.IntegerField(default=0)),
                ("icon", models.CharField(max_length=64, null=True)),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#FFFFFF",
                        image_field=None,
                        max_length=18,
                        samples=[
                            ("#ffffff", "white"),
                            ("#ff6b22", "orange"),
                            ("#cddc39", "lime"),
                            ("#b9b9b9", "grey"),
                            ("#af2422", "red"),
                            ("#673ab7", "purple"),
                            ("#4cd964", "green"),
                            ("#2196f3", "blue"),
                            ("#009688", "dark teal"),
                        ],
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_categories",
                        to="transactions.transactioncategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.BigIntegerField()),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "Usd"),
                            ("EUR", "Eur"),
                            ("BYN", "Byn"),
                            ("RUB", "Rub"),
                        ],
                        max_length=3,
                    ),
                ),
                ("comment", models.CharField(max_length=255, null=True)),
                (
                    "transaction_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="transactions.transactioncategory",
                    ),
                ),
            ],
        ),
    ]
